import { StyleSheet } from "react-native";

export const formStyles = StyleSheet.create({
  fieldLabel: { marginBottom: 7, color: "#4C4037", fontSize: 15, fontWeight: "800" },
  input: {
    minHeight: 52,
    marginBottom: 16,
    paddingHorizontal: 15,
    borderWidth: 2,
    borderColor: "#E5D8C8",
    borderRadius: 15,
    color: "#342D28",
    backgroundColor: "#FFFCF7",
    fontSize: 17,
  },
  codeInput: {
    textAlign: "center",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 8,
  },
  providerButton: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginBottom: 14,
    borderWidth: 2,
    borderColor: "#D8D3CC",
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
  },
  providerIcon: { color: "#4285F4", fontSize: 20, fontWeight: "900" },
  providerButtonText: { color: "#342D28", fontSize: 16, fontWeight: "800" },
  separatorText: {
    marginBottom: 16,
    color: "#887A70",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  primaryButton: {
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
    borderRadius: 17,
    backgroundColor: "#2D8C7C",
  },
  primaryButtonText: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" },
  secondaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    borderRadius: 15,
    backgroundColor: "#EAF5F2",
  },
  secondaryButtonText: { color: "#216D61", fontSize: 16, fontWeight: "800" },
  textButton: { alignItems: "center", marginTop: 10, padding: 10 },
  textButtonText: { color: "#795D51", fontSize: 14, fontWeight: "800" },
  disabled: { opacity: 0.45 },
  error: {
    marginBottom: 14,
    padding: 12,
    borderRadius: 12,
    color: "#8A3838",
    backgroundColor: "#FCE6E3",
    fontWeight: "700",
  },
  success: {
    marginBottom: 14,
    padding: 12,
    borderRadius: 12,
    color: "#23665B",
    backgroundColor: "#E4F4EF",
    fontWeight: "700",
  },
  helper: { marginTop: -8, marginBottom: 15, color: "#776A60", fontSize: 13, lineHeight: 18 },
  row: { flexDirection: "row", gap: 12 },
  rowField: { flex: 1 },
});
